#!/usr/bin/python3
import webbrowser
import sys
import pyperclip

def open_in_browser():
    """Search for a given text string on the internet.
    Usage: Just type the name of the program, and desired text string afterward.
    Or copy text to the clipboard and write two dots
    to search for text from the clipboard. """
    search_string = str(pyperclip.paste()) if sys.argv[1] == ".." else ' '.join(sys.argv[1:])
    if search_string.endswith(' $'):
        search_string = search_string.replace(' $', ' related:stackoverflow.com')

    webbrowser.open(f'https://lite.duckduckgo.com/lite/?q={search_string}')
open_in_browser()
