#!/bin/bash

REAL_BIN_PATH="$(readlink -e "${0}")" # resolve symlink
REAL_BIN_PATH="$(dirname "${REAL_BIN_PATH}")" # get base

declare -a dirs
dirs=(
    "git"
    "certs_sha"
    "development"
    "perf"
)
printf "General tools:\n"
for i in "${dirs[@]}"; do
    printf "export PATH=%s/%s:\$PATH\n" "${REAL_BIN_PATH}" "${i}"
done

printf "\nMore perf tools:\n"
declare -a perf_dirs
perf_dirs=(
    "perf"
    "perf/hw"
    "perf/load"
    "perf/net"
    "perf/sec"
)
for i in "${perf_dirs[@]}"; do
    printf "export PATH=%s/%s:\$PATH\n" "${REAL_BIN_PATH}" "${i}"
done
