#!/bin/bash
#xdg-open $HOME/adrian_knihy/zoznam_záložky/man/tldr-book.pdf&
# To get help try apropos. apropos seare manual page names and descriptions.


finpath=$HOME/adrian_knihy/zoznam_záložky/man/tldr/
cd $finpath
find -name "${1}".md | xargs batcat --pager "less -RF"






