#!/bin/sh
BKPDIR="/mnt/c/Users/AdriánBíro/src/"
#tar -cf ${BKPDIR}/homeadrian.tar --listed-incremental=${BKPDIR}/metadatahomeadrian.snar /home/adrian
tar -cf ${BKPDIR}/homeadrian.tar /home/adrian
# restore
# tar --directory=/home/ -xf ${BKPDIR}/homeadrian.tar --listed-incremental=/dev/null
