#!/bin/bash
HINT_NAME=$1
DESIRED_STRING=$2
MIN_ARGS=2

# Argument check
if [ "$#" -lt $MIN_ARGS ]; then
	echo "Try it again like this: hint <name.hint> <text string>"
	exit 1
fi
# This will search in plain text files with .hint extension, and print one line after string because my formatting conventions for these are: description in the first line and syntax on following.
cat ~/bin/gits/hints/$1 | grep -A 1 $2

exit 0
