#!/bin/bash

mkdir -p zmaz/zdir{1..3}/bdir{1..3}

touch zmaz/zdir{1..3}/bdir{1..3}/file{1..5}.txt
touch zmaz/file{1..5}.txt

if [[ "$1" == "-ls" ]]; then
  ls -R | less
fi

if [[ "$1" == "-rm" ]]; then
  rm -r zmaz
fi

if [[ "$1" == "-m" ]]; then
  touch -m zmaz/zdir{1..3}/bdir{1..3}/file{1..2}.txt
  touch -m zmaz/file{1..2}.txt
fi
