#!/usr/bin/python3
import subprocess
import sys
import os

def open_csv(file_name):
    if file_name.endswith(".csv"):
        subprocess.call(["libreoffice", "--view", "--minimized", "--quickstart", file_name])
    else:
        print(f"{file_name} isn't valid CSV.")
        sys.exit(2)

def list_csv():
    files = []
    for i in os.listdir('.'):
        if i.endswith(".csv"):
            files.append(i)
    if len(files) == 1:
        open_csv(files[0])
    else:
        print("Give a CSV file to open as an argument.")
        sys.exit(2)

def main():
    if len(sys.argv) > 1:
        open_csv(sys.argv[1])
    else:
        list_csv()

if __name__ == "__main__":
    main()
