#!/usr/bin/python3
import os
import shutil

zo = []
mtup = ("venv", "__pycache__")

for (root, dirs, files) in os.walk('.'):
	if os.path.basename(root) in mtup:
		zo.append((os.path.relpath(root)))

print(f'Should I remove these files?')
for i in zo:
    print(f'./{i}')
#    print(os.path.join(os.path.basename(os.getcwd()), i))

response = input("Y/N ").upper().strip()
try:
    if response == "Y":
        for i in zo:
            shutil.rmtree(i)
except FileNotFoundError:
    pass
