#!/usr/bin/python3
import argparse
import hashlib
import pyperclip

parser = argparse.ArgumentParser()
parser.add_argument('file_name', help='Copy sum for comparing to clipboard, and specify the file name as an argument.', type=str)
parser.add_argument('-md5', '--md5sum', help='for md5sum', action='store_true')
args = parser.parse_args()

file_name = args.file_name
sum_to_compare = str(pyperclip.paste())

with open(file_name, "rb") as f:
    bytes = f.read()
    if args.md5sum:
        testsum = hashlib.md5(bytes).hexdigest()
    else:
        testsum = hashlib.sha256(bytes).hexdigest()

if testsum == sum_to_compare:
    print("File is corect")
else:
    print("Sums difer chceck it")

print(f'{sum_to_compare}\tsum from the clipboard.')
print(f'{testsum}\tsum from the clipboard.')
