#!/bin/bash
# to browse PDF version of https://github.com/tldr-pages/tldr
xdg-open $HOME/adrian_knihy/zoznam_záložky/man/tldr-book.pdf&
# To get help whitout thist try apropos. apropos search the manual page names and descriptions.
