#!/usr/bin/awk -f
function archtype(string) {
switch (string) {
    case  "tar" :
        unarchstr =  "tar x[z]vf file.tar" ; break
    case "lzma" :
        unarchstr =  "unlzma file.lzma" ; break
    case "bz2" :
        unarchstr =  "bunzip2 file.bz2" ; break
    case "rar" :
        unarchstr =  "unrar file.rar" ; break
    case "gz" :
        unarchstr =  "gunzip file.gz" ; break
    case "zip" :
        unarchstr =  "unzip file.zip" ; break
    case "z" :
        unarchstr =  "uncompress file.z" ; break
    case "7z" :
        unarchstr =  "7z x file.7z" ; break
    case "xz" :
        unarchstr =  "unxz file.xz" ; break
    case "exe" :
        unarchstr =  "cabextract file.exe" ; break

    default:
        unarchstr = "Unknow extension: " string
        usage();
        break
    }
    return unarchstr
}

function usage() {
    print "Usage: unarcheat [tar|gz|zip]"
}

BEGIN {
    if (ARGC > 1){
        file_arg = ARGV[1];
        delete ARGV[1];
        unarchcmd = archtype(file_arg)
    } else {
        usage()
        exit(1)
    }
    print unarchcmd
}
