#!/usr/bin/awk -f
function archtype(string) {
# https://www.gnu.org/software/gawk/manual/html_node/Strong-Regexp-Constants.html
switch (string) {
    case @/(\.tar\.bz2|\.tar\.gz|\.tar\.xz|\.tar)$/ :
        unarchstr =  "tar x[z]vf " string ; break
    case @/\.lzma$/ :
        unarchstr =  "unlzma " string ; break
    case @/\.bz2$/ :
        unarchstr =  "bunzip2 " string ; break
    case @/\.rar$/ :
        unarchstr =  "unrar " string ; break
    case @/\.gz$/ :
        unarchstr =  "gunzip " string ; break
    case @/\.zip$/ :
        unarchstr =  "unzip " string ; break
    case @/\.z$/ :
        unarchstr =  "uncompress " string ; break
    case @/\.7z$/ :
        unarchstr =  "7z x " string ; break
    case @/\.xz$/ :
        unarchstr =  "unxz " string ; break
    case @/\.exe$/ :
        unarchstr =  "cabextract " string ; break

    default:
        unarchstr = "Unknow extension: " string
        usage();
        break
    }
    return unarchstr
}

function usage() {
    print "Usage: unarcheat [tar|gz|zip]"
}

BEGIN {
    if (ARGC > 1){
        file_arg = ARGV[1];
        delete ARGV[1];
        unarchcmd = archtype(file_arg)
    } else {
        usage()
        exit(1)
    }
    print unarchcmd
}
