#!/bin/bash
echo 3 | sudo tee '/proc/sys/vm/drop_caches' && swapoff -a && swapon -a && printf '\n%s\n' 'Ram-cache and Swap Cleared'


:<<'END_COMMENT'
https://www.kernel.org/doc/Documentation/sysctl/vm.txt
drop_caches

Writing to this will cause the kernel to drop clean caches, as well as
reclaimable slab objects like dentries and inodes.  Once dropped, their
memory becomes free.

swap[off|on] 
enable/disable devices and files for paging 
a, --all All devices marked as "swap" in /etc/fstab

END_COMMENT
