#!/bin/sh

echo "${@}" | grep -Eq '[-]{2}\w' && printf "Use just short options like -f, not longlike --forest\n" && exit 1

[ $# -gt 0 ] && userflags="$(echo "$@" | sed 's/[  -]//g')" # -fe to fe

#SYSV or BSD ps?
if ps aux >/dev/null 2>&1; then
    defaults="auxww"
    timecolumn=9 
else
    defaults="-ef"
    timecolumn=5
fi

ps "${defaults}${userflags}" | awk -v timecolumn="${timecolumn}" '$timecolumn ~ /^[a-zA-Z][a-z][a-z]/' | sort
