#!/bin/bash
#https://man7.org/linux/man-pages/man5/slabinfo.5.html
#https://linux-mm.org/OOM

#What objects is taking the most space
awk '{printf "%-30s %5d MB\n", $1 ,$3*$4/(1024*1024)}' < /proc/slabinfo | sort -nr -k2