#!/bin/sh

vmstat  -Sm 1

:<<'END_COMMENT'
Report virtual memory statistics
-S, --unit character
    Switches outputs between 1000 (k), 1024 (K), 1000000 (m), or 1048576 (M) bytes.  
    Note this does not change the block (bi/bo) fields, which are always measured in blocks.
-m, --slabs
    Displays slabinfo.
END_COMMENT