#!/bin/bash

case "${1}" in
*.tar) tar tvvf "${1}" 2>/dev/null ;;
*.tgz) tar tzvvf "${1}" 2>/dev/null ;;
*.tar.bz2) bzip2 -cd "${1}" "${1}" 2>/dev/null | tar tvvf - ;;
*.tar.gz) tar tzvvf "${1}" 2>/dev/null ;;
*.tar.Z) tar tzvvf "${1}" 2>/dev/null ;;
*.tar.z) tar tzvvf "${1}" 2>/dev/null ;;
*.bz2) bzip2 -dc "${1}" 2>/dev/null ;;
*.Z) gzip -dc "${1}" 2>/dev/null ;;
*.z) gzip -dc "${1}" 2>/dev/null ;;
*.gz) gzip -dc "${1}" 2>/dev/null ;;
*.zip) unzip -l "${1}" 2>/dev/null ;;
*.1 | *.2 | *.3 | *.4 | *.5 | *.6 | *.7 | *.8 | *.9 | *.n | *.man)
    if [[ "$(file -L "${1}" | cut -d ' ' -f 2)" = "troff" ]]; then
        groff -s -p -t -e -Tascii -mandoc "${1}"
    fi
    ;;
*) file -L "${1}" 2>/dev/null ;;
esac
