#!/bin/bash

# escape \ip to overwrite alias
{
    echo '. Interface . | Bytes Packets Errors Droped Missed Mcast | . | Bytes Packets Errors Droped Carrier Collsns'
    \ip -human -oneline -statistics link show | sed -e 's/<.* RX:/RX:/' \
        -e 's/bytes.*mcast//' \
        -e 's/bytes.*collsns//' \
        -e 's/\\  *altname.*//' \
        -e 's/  *$//' \
        -e 's/\\/\|/g'
} | column -t

docs=: <<'END_COMMENT'
ip-link - network device configuration
-o  -oneline    output each record on a single line,
END_COMMENT

# [ $# -gt 0 ] &&
# watch -n 1
# watch -d
