#!/bin/bash

lsof -Pan -i -p $(pgrep "${1}") 

docs=:<<'END_COMMENT'
List open files
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
firefox-b 4408 adrian  151u  IPv4  54667      0t0  TCP 10.0.1.21:44218->34.117.65.55:443 (ESTABLISHED)

-n    inhibits the conversion of network numbers to host names for network files.
-p    process 
END_COMMENT