#!/bin/bash

lsof -Pan -i -p $(pgrep "${1}") 

:<<'END_COMMENT'
List open files
COMMAND    PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
firefox-b 4408 adrian  151u  IPv4  54667      0t0  TCP 10.0.1.21:44218->34.117.65.55:443 (ESTABLISHED)

-n    inhibits the conversion of network numbers to host names for network files.
-p    process 
-i [i]  selects the listing of files any of whose Internet address matches the address specified in i.  
        If no address is  specified,  this  option selects the listing of all Internet network files.
END_COMMENT