#!/bin/sh

route -n -A inet6

: <<'END_COMMENT'
route - show / manipulate the IP routing table
like route -n
cf. diff <(route -n -A inet) <(route -n)
-A family
    use the specified address family.
-n     show  numerical  addresses instead of host names.  
END_COMMENT