#!/bin/bash
[[ $# -eq 0 ]] && {
    echo -e "Usage:\n\t${0##*/} (bios|system|baseboard|chassis|processor|memory|cache|connector|slot)"
    exit 1
}
function _sudo() {
    if ((0 == "$(id --user)")); then
        "$@"
    else
        sudo "$@"
    fi
}

_sudo dmidecode -t "${1}"


docs=:<<'END_COMMENT'
DMI table decoder
It is tool  for dumping a computer's DMI (some say SMBIOS) table contents in a human-readable format. 
This table contains a description of the system's hardware components, as well as other useful pieces 
of information such as  serial  numbers  and  BIOS  revision.
-t, --type TYPE
END_COMMENT