#!/bin/bash
function _sudo() {
    if ((0 == "$(id --user)")); then
        "$@"
    else
        sudo "$@"
    fi
}
# -vv verbose
# -D Always show PCI domain numbers
# -Q Query the central database even for entries which are recognized locally.
# -nn Show PCI vendor and device codes as both numbers and names.
_sudo lspci -vvDQnn
